<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class StatistikController extends Controller
{
    public function index()
    {
        $tgl = Carbon::now();
        $tgl_now = $tgl->format('Y-m-d');
        $icats = DB::table('wp_terms')
            ->join('wp_term_taxonomy', 'wp_terms.term_id', '=', 'wp_term_taxonomy.term_id')
            ->join('wp_term_relationships', 'wp_term_taxonomy.term_taxonomy_id', '=', 'wp_term_relationships.term_taxonomy_id')
            ->join('wp_posts', 'wp_posts.ID', '=', 'wp_term_relationships.object_id')
            ->join('wp_w2gm_locations_relationships', 'wp_posts.ID', '=', 'wp_w2gm_locations_relationships.post_id')
            ->join('wp_lokasi', 'wp_w2gm_locations_relationships.location_id', '=', 'wp_lokasi.lokasi_id')
            ->select('wp_posts.ID', 'wp_posts.post_title', 'wp_w2gm_locations_relationships.address_line_1', 'wp_lokasi.lokasi_name', 'wp_lokasi.province_name', 'wp_w2gm_locations_relationships.map_coords_1', 'wp_w2gm_locations_relationships.map_coords_2', 'wp_terms.name AS incident_category', 'wp_w2gm_locations_relationships.number_of_incident', 'wp_w2gm_locations_relationships.number_of_injuries', 'wp_w2gm_locations_relationships.number_of_fatalities', 'wp_w2gm_locations_relationships.additional_info', 'wp_posts.post_date', 'wp_terms.name') 
            ->where('wp_posts.post_status', 'publish')
            ->whereDate(DB::raw('DATE(wp_posts.post_date)'), $tgl_now)
            ->where(function($query) {
                $query->where('wp_terms.term_id', 392)
                      ->orWhere('wp_terms.term_id', 433)
                      ->orWhere('wp_terms.term_id', 391);
            })
            ->get();

        $itypes = DB::table('wp_w2gm_locations_relationships')
            ->join('wp_term_relationships', 'wp_term_relationships.object_id', '=', 'wp_w2gm_locations_relationships.post_id')
            ->join('wp_term_taxonomy', 'wp_term_taxonomy.term_taxonomy_id', '=', 'wp_term_relationships.term_taxonomy_id')
            ->join('wp_terms', 'wp_terms.term_id', '=', 'wp_term_taxonomy.term_id')
            ->join('wp_posts', 'wp_posts.ID', '=', 'wp_w2gm_locations_relationships.post_id')
            ->select('wp_w2gm_locations_relationships.post_id', 'wp_terms.name', 'wp_posts.post_date') 
            ->whereDate(DB::raw('DATE(wp_posts.post_date)'), $tgl_now)
            ->where(function($query) {
                $query->where('wp_terms.term_id', 434)
                      ->orWhere('wp_terms.term_id', 435)
                      ->orWhere('wp_terms.term_id', 8065)
                      ->orWhere('wp_terms.term_id', 6829)
                      ->orWhere('wp_terms.term_id', 16127)
                      ->orWhere('wp_terms.term_id', 16126)
                      ->orWhere('wp_terms.term_id', 480)
                      ->orWhere('wp_terms.term_id', 438)
                      ->orWhere('wp_terms.term_id', 436)
                      ->orWhere('wp_terms.term_id', 479)
                      ->orWhere('wp_terms.term_id', 437);
            })
            ->get();

        $sutypes = DB::table('wp_w2gm_locations_relationships')
            ->join('wp_term_relationships', 'wp_term_relationships.object_id', '=', 'wp_w2gm_locations_relationships.post_id')
            ->join('wp_term_taxonomy', 'wp_term_taxonomy.term_taxonomy_id', '=', 'wp_term_relationships.term_taxonomy_id')
            ->join('wp_terms', 'wp_terms.term_id', '=', 'wp_term_taxonomy.term_id')
            ->join('wp_posts', 'wp_posts.ID', '=', 'wp_w2gm_locations_relationships.post_id')
            ->select('wp_w2gm_locations_relationships.post_id', 'wp_terms.name', 'wp_posts.post_date') 
            ->whereDate(DB::raw('DATE(wp_posts.post_date)'), $tgl_now)
            ->where(function($query) {
                $query->where('wp_terms.term_id', 6827)
                        ->orwhere('wp_terms.term_id', 6828)
                        ->orwhere('wp_terms.term_id', 16117)
                        ->orwhere('wp_terms.term_id', 6826)
                        ->orwhere('wp_terms.term_id', 16332)
                        ->orwhere('wp_terms.term_id', 16121)
                        ->orwhere('wp_terms.term_id', 16123)
                        ->orwhere('wp_terms.term_id', 16125)
                        ->orwhere('wp_terms.term_id', 16122)
                        ->orwhere('wp_terms.term_id', 16119)
                        ->orwhere('wp_terms.term_id', 16120)
                        ->orwhere('wp_terms.term_id', 16124)
                        ->orwhere('wp_terms.term_id', 16147)
                        ->orwhere('wp_terms.term_id', 485)
                        ->orwhere('wp_terms.term_id', 16251)
                        ->orwhere('wp_terms.term_id', 451)
                        ->orwhere('wp_terms.term_id', 16250)
                        ->orwhere('wp_terms.term_id', 487)
                        ->orwhere('wp_terms.term_id', 486)
                        ->orwhere('wp_terms.term_id', 453)
                        ->orwhere('wp_terms.term_id', 452)
                        ->orwhere('wp_terms.term_id', 458)
                        ->orwhere('wp_terms.term_id', 7196)
                        ->orwhere('wp_terms.term_id', 466)
                        ->orwhere('wp_terms.term_id', 16191)
                        ->orwhere('wp_terms.term_id', 461)
                        ->orwhere('wp_terms.term_id', 460)
                        ->orwhere('wp_terms.term_id', 16207)
                        ->orwhere('wp_terms.term_id', 463)
                        ->orwhere('wp_terms.term_id', 467)
                        ->orwhere('wp_terms.term_id', 464)
                        ->orwhere('wp_terms.term_id', 459)
                        ->orwhere('wp_terms.term_id', 5418)
                        ->orwhere('wp_terms.term_id', 16192)
                        ->orwhere('wp_terms.term_id', 462)
                        ->orwhere('wp_terms.term_id', 16193)
                        ->orwhere('wp_terms.term_id', 465) 
                        ->orwhere('wp_terms.term_id', 679)
                        ->orwhere('wp_terms.term_id', 16190)
                        ->orwhere('wp_terms.term_id', 16189)
                        ->orwhere('wp_terms.term_id', 481)
                        ->orwhere('wp_terms.term_id', 7347)
                        ->orwhere('wp_terms.term_id', 16240)
                        ->orwhere('wp_terms.term_id', 484)
                        ->orwhere('wp_terms.term_id', 5868)
                        ->orwhere('wp_terms.term_id', 16246)
                        ->orwhere('wp_terms.term_id', 16248)
                        ->orwhere('wp_terms.term_id', 16242)
                        ->orwhere('wp_terms.term_id', 16243)
                        ->orwhere('wp_terms.term_id', 482)
                        ->orwhere('wp_terms.term_id', 483)
                        ->orwhere('wp_terms.term_id', 16244)
                        ->orwhere('wp_terms.term_id', 16247)
                        ->orwhere('wp_terms.term_id', 16245)
                        ->orwhere('wp_terms.term_id', 8139)
                        ->orwhere('wp_terms.term_id', 16241)
                        ->orwhere('wp_terms.term_id', 447)
                        ->orwhere('wp_terms.term_id', 16234)
                        ->orwhere('wp_terms.term_id', 16230)
                        ->orwhere('wp_terms.term_id', 478)
                        ->orwhere('wp_terms.term_id', 5869)
                        ->orwhere('wp_terms.term_id', 16238)
                        ->orwhere('wp_terms.term_id', 16231)
                        ->orwhere('wp_terms.term_id', 16233)
                        ->orwhere('wp_terms.term_id', 16235)
                        ->orwhere('wp_terms.term_id', 448)
                        ->orwhere('wp_terms.term_id', 449)
                        ->orwhere('wp_terms.term_id', 16236)
                        ->orwhere('wp_terms.term_id', 16239)
                        ->orwhere('wp_terms.term_id', 16237)
                        ->orwhere('wp_terms.term_id', 16249)
                        ->orwhere('wp_terms.term_id', 16232);
            })
            ->get();

            $sconflicts = DB::table('wp_w2gm_locations_relationships')
                ->join('wp_term_relationships', 'wp_term_relationships.object_id', '=', 'wp_w2gm_locations_relationships.post_id')
                ->join('wp_term_taxonomy', 'wp_term_taxonomy.term_taxonomy_id', '=', 'wp_term_relationships.term_taxonomy_id')
                ->join('wp_terms', 'wp_terms.term_id', '=', 'wp_term_taxonomy.term_id')
                ->join('wp_posts', 'wp_posts.ID', '=', 'wp_w2gm_locations_relationships.post_id')
                ->select('wp_w2gm_locations_relationships.post_id', 'wp_terms.name') 
                ->whereDate(DB::raw('DATE(wp_posts.post_date)'), $tgl_now)
                ->where(function($query) {
                    $query->where('wp_terms.term_id', 16200)
                          ->orWhere('wp_terms.term_id', 16203)
                          ->orWhere('wp_terms.term_id', 16204)
                          ->orWhere('wp_terms.term_id', 16197)
                          ->orWhere('wp_terms.term_id', 16205)
                          ->orWhere('wp_terms.term_id', 16199)
                          ->orWhere('wp_terms.term_id', 16194)
                          ->orWhere('wp_terms.term_id', 16196)
                          ->orWhere('wp_terms.term_id', 16202)
                          ->orWhere('wp_terms.term_id', 16206)
                          ->orWhere('wp_terms.term_id', 16198)
                          ->orWhere('wp_terms.term_id', 16195)
                          ->orWhere('wp_terms.term_id', 16201);
                     })
                ->get();
            
            $weapontypes = DB::table('wp_w2gm_locations_relationships')
                ->join('wp_term_relationships', 'wp_term_relationships.object_id', '=', 'wp_w2gm_locations_relationships.post_id')
                ->join('wp_term_taxonomy', 'wp_term_taxonomy.term_taxonomy_id', '=', 'wp_term_relationships.term_taxonomy_id')
                ->join('wp_terms', 'wp_terms.term_id', '=', 'wp_term_taxonomy.term_id')
                ->join('wp_posts', 'wp_posts.ID', '=', 'wp_w2gm_locations_relationships.post_id')
                ->select('wp_w2gm_locations_relationships.post_id', 'wp_terms.name') 
                ->whereDate(DB::raw('DATE(wp_posts.post_date)'), $tgl_now)
                ->where(function($query) {
                    $query->where('wp_terms.term_id', 16142)
                        ->orWhere('wp_terms.term_id', 16143)
                        ->orWhere('wp_terms.term_id', 16144)
                        ->orWhere('wp_terms.term_id', 16135)
                        ->orWhere('wp_terms.term_id', 16145)
                        ->orWhere('wp_terms.term_id', 16146)
                        ->orWhere('wp_terms.term_id', 5867)
                        ->orWhere('wp_terms.term_id', 1713)
                        ->orWhere('wp_terms.term_id', 16391)
                        ->orWhere('wp_terms.term_id', 16392)
                        ->orWhere('wp_terms.term_id', 16393)
                        ->orWhere('wp_terms.term_id', 16394)
                        ->orWhere('wp_terms.term_id', 16368)
                        ->orWhere('wp_terms.term_id', 16395)
                        ->orWhere('wp_terms.term_id', 16396)
                        ->orWhere('wp_terms.term_id', 16136)
                        ->orWhere('wp_terms.term_id', 16397)
                        ->orWhere('wp_terms.term_id', 16398)
                        ->orWhere('wp_terms.term_id', 16399)
                        ->orWhere('wp_terms.term_id', 16400)
                        ->orWhere('wp_terms.term_id', 16133)
                        ->orWhere('wp_terms.term_id', 16401)
                        ->orWhere('wp_terms.term_id', 16134)
                        ->orWhere('wp_terms.term_id', 16367)
                        ->orWhere('wp_terms.term_id', 16402);
                    })
                ->get();
            
            $actors = DB::table('wp_w2gm_locations_relationships')
                ->join('wp_term_relationships', 'wp_term_relationships.object_id', '=', 'wp_w2gm_locations_relationships.post_id')
                ->join('wp_term_taxonomy', 'wp_term_taxonomy.term_taxonomy_id', '=', 'wp_term_relationships.term_taxonomy_id')
                ->join('wp_terms', 'wp_terms.term_id', '=', 'wp_term_taxonomy.term_id')
                ->join('wp_posts', 'wp_posts.ID', '=', 'wp_w2gm_locations_relationships.post_id')
                ->select('wp_w2gm_locations_relationships.post_id', 'wp_terms.name') 
                ->whereDate(DB::raw('DATE(wp_posts.post_date)'), $tgl_now)
                ->where(function($query) {
                    $query->where('wp_terms.term_id', 16165)
                        ->orWhere('wp_terms.term_id', 16152)
                        ->orWhere('wp_terms.term_id', 16158)
                        ->orWhere('wp_terms.term_id', 16159)
                        ->orWhere('wp_terms.term_id', 16153)
                        ->orWhere('wp_terms.term_id', 16169)
                        ->orWhere('wp_terms.term_id', 16150)
                        ->orWhere('wp_terms.term_id', 16163)
                        ->orWhere('wp_terms.term_id', 16162)
                        ->orWhere('wp_terms.term_id', 16161)
                        ->orWhere('wp_terms.term_id', 16166)
                        ->orWhere('wp_terms.term_id', 16170)
                        ->orWhere('wp_terms.term_id', 16167)
                        ->orWhere('wp_terms.term_id', 16168)
                        ->orWhere('wp_terms.term_id', 16151)
                        ->orWhere('wp_terms.term_id', 16156)
                        ->orWhere('wp_terms.term_id', 16157)
                        ->orWhere('wp_terms.term_id', 16171)
                        ->orWhere('wp_terms.term_id', 16160)
                        ->orWhere('wp_terms.term_id', 16369)
                        ->orWhere('wp_terms.term_id', 16164);
                    })
                ->get();
            
            $actortypes = DB::table('wp_w2gm_locations_relationships')
                ->join('wp_term_relationships', 'wp_term_relationships.object_id', '=', 'wp_w2gm_locations_relationships.post_id')
                ->join('wp_term_taxonomy', 'wp_term_taxonomy.term_taxonomy_id', '=', 'wp_term_relationships.term_taxonomy_id')
                ->join('wp_terms', 'wp_terms.term_id', '=', 'wp_term_taxonomy.term_id')
                ->join('wp_posts', 'wp_posts.ID', '=', 'wp_w2gm_locations_relationships.post_id')
                ->select('wp_w2gm_locations_relationships.post_id', 'wp_terms.name') 
                ->whereDate(DB::raw('DATE(wp_posts.post_date)'), $tgl_now)
                ->where(function($query) {
                    $query->where('wp_terms.term_id', 16155)
                        ->orWhere('wp_terms.term_id', 16154)
                        ->orWhere('wp_terms.term_id', 16173)
                        ->orWhere('wp_terms.term_id', 16174)
                        ->orWhere('wp_terms.term_id', 16172)
                        ->orWhere('wp_terms.term_id', 16175)
                        ->orWhere('wp_terms.term_id', 16335)
                        ->orWhere('wp_terms.term_id', 16334)
                        ->orWhere('wp_terms.term_id', 16176)
                        ->orWhere('wp_terms.term_id', 16177)
                        ->orWhere('wp_terms.term_id', 16178)
                        ->orWhere('wp_terms.term_id', 16333)
                        ->orWhere('wp_terms.term_id', 16179)
                        ->orWhere('wp_terms.term_id', 16180)
                        ->orWhere('wp_terms.term_id', 16181);
                    })
                ->get();
            
            $targets = DB::table('wp_w2gm_locations_relationships')
                ->join('wp_term_relationships', 'wp_term_relationships.object_id', '=', 'wp_w2gm_locations_relationships.post_id')
                ->join('wp_term_taxonomy', 'wp_term_taxonomy.term_taxonomy_id', '=', 'wp_term_relationships.term_taxonomy_id')
                ->join('wp_terms', 'wp_terms.term_id', '=', 'wp_term_taxonomy.term_id')
                ->join('wp_posts', 'wp_posts.ID', '=', 'wp_w2gm_locations_relationships.post_id')
                ->select('wp_w2gm_locations_relationships.post_id', 'wp_terms.name') 
                ->whereDate(DB::raw('DATE(wp_posts.post_date)'), $tgl_now)
                ->where(function($query) {
                    $query->where('wp_terms.term_id', 16223)
                        ->orWhere('wp_terms.term_id', 16211)
                        ->orWhere('wp_terms.term_id', 16216)
                        ->orWhere('wp_terms.term_id', 16217)
                        ->orWhere('wp_terms.term_id', 16227)
                        ->orWhere('wp_terms.term_id', 16209)
                        ->orWhere('wp_terms.term_id', 16221)
                        ->orWhere('wp_terms.term_id', 16220)
                        ->orWhere('wp_terms.term_id', 16213)
                        ->orWhere('wp_terms.term_id', 16219)
                        ->orWhere('wp_terms.term_id', 16224)
                        ->orWhere('wp_terms.term_id', 16228)
                        ->orWhere('wp_terms.term_id', 16212)
                        ->orWhere('wp_terms.term_id', 16225)
                        ->orWhere('wp_terms.term_id', 16226)
                        ->orWhere('wp_terms.term_id', 16210)
                        ->orWhere('wp_terms.term_id', 16214)
                        ->orWhere('wp_terms.term_id', 16215)
                        ->orWhere('wp_terms.term_id', 16229)
                        ->orWhere('wp_terms.term_id', 16218)
                        ->orWhere('wp_terms.term_id', 16403)
                        ->orWhere('wp_terms.term_id', 16222);
                    })
                ->get();
            
            $tartypes = DB::table('wp_w2gm_locations_relationships')
                ->join('wp_term_relationships', 'wp_term_relationships.object_id', '=', 'wp_w2gm_locations_relationships.post_id')
                ->join('wp_term_taxonomy', 'wp_term_taxonomy.term_taxonomy_id', '=', 'wp_term_relationships.term_taxonomy_id')
                ->join('wp_terms', 'wp_terms.term_id', '=', 'wp_term_taxonomy.term_id')
                ->join('wp_posts', 'wp_posts.ID', '=', 'wp_w2gm_locations_relationships.post_id')
                ->select('wp_w2gm_locations_relationships.post_id', 'wp_terms.name') 
                ->whereDate(DB::raw('DATE(wp_posts.post_date)'), $tgl_now)
                ->where(function($query) {
                    $query->where('wp_terms.term_id', 16448)
                        ->orWhere('wp_terms.term_id', 16252)
                        ->orWhere('wp_terms.term_id', 16253)
                        ->orWhere('wp_terms.term_id', 16254)
                        ->orWhere('wp_terms.term_id', 16259)
                        ->orWhere('wp_terms.term_id', 16272)
                        ->orWhere('wp_terms.term_id', 16257)
                        ->orWhere('wp_terms.term_id', 16314)
                        ->orWhere('wp_terms.term_id', 16263)
                        ->orWhere('wp_terms.term_id', 16260)
                        ->orWhere('wp_terms.term_id', 16261)
                        ->orWhere('wp_terms.term_id', 16262)
                        ->orWhere('wp_terms.term_id', 16267)
                        ->orWhere('wp_terms.term_id', 16264)
                        ->orWhere('wp_terms.term_id', 16265)
                        ->orWhere('wp_terms.term_id', 16266)
                        ->orWhere('wp_terms.term_id', 16271)
                        ->orWhere('wp_terms.term_id', 16268)
                        ->orWhere('wp_terms.term_id', 16269)
                        ->orWhere('wp_terms.term_id', 16270)
                        ->orWhere('wp_terms.term_id', 16275)
                        ->orWhere('wp_terms.term_id', 16256)
                        ->orWhere('wp_terms.term_id', 16273)
                        ->orWhere('wp_terms.term_id', 16274)
                        ->orWhere('wp_terms.term_id', 16279)
                        ->orWhere('wp_terms.term_id', 16276)
                        ->orWhere('wp_terms.term_id', 16277)
                        ->orWhere('wp_terms.term_id', 16278)
                        ->orWhere('wp_terms.term_id', 16283)
                        ->orWhere('wp_terms.term_id', 16280)
                        ->orWhere('wp_terms.term_id', 16281)
                        ->orWhere('wp_terms.term_id', 16282)
                        ->orWhere('wp_terms.term_id', 16287)
                        ->orWhere('wp_terms.term_id', 16284)
                        ->orWhere('wp_terms.term_id', 16285)
                        ->orWhere('wp_terms.term_id', 16286)
                        ->orWhere('wp_terms.term_id', 16291)
                        ->orWhere('wp_terms.term_id', 16288)
                        ->orWhere('wp_terms.term_id', 16289)
                        ->orWhere('wp_terms.term_id', 16290)
                        ->orWhere('wp_terms.term_id', 16295)
                        ->orWhere('wp_terms.term_id', 16292)
                        ->orWhere('wp_terms.term_id', 16293)
                        ->orWhere('wp_terms.term_id', 16294)
                        ->orWhere('wp_terms.term_id', 16299)
                        ->orWhere('wp_terms.term_id', 16296)
                        ->orWhere('wp_terms.term_id', 16297)
                        ->orWhere('wp_terms.term_id', 16298)
                        ->orWhere('wp_terms.term_id', 16303)
                        ->orWhere('wp_terms.term_id', 16300)
                        ->orWhere('wp_terms.term_id', 16301)
                        ->orWhere('wp_terms.term_id', 16302)
                        ->orWhere('wp_terms.term_id', 16307)
                        ->orWhere('wp_terms.term_id', 16304)
                        ->orWhere('wp_terms.term_id', 16305)
                        ->orWhere('wp_terms.term_id', 16306)
                        ->orWhere('wp_terms.term_id', 16311)
                        ->orWhere('wp_terms.term_id', 16308)
                        ->orWhere('wp_terms.term_id', 16309)
                        ->orWhere('wp_terms.term_id', 16310)
                        ->orWhere('wp_terms.term_id', 16315)
                        ->orWhere('wp_terms.term_id', 16312)
                        ->orWhere('wp_terms.term_id', 16313)
                        ->orWhere('wp_terms.term_id', 16319)
                        ->orWhere('wp_terms.term_id', 16316)
                        ->orWhere('wp_terms.term_id', 16317)
                        ->orWhere('wp_terms.term_id', 16318)
                        ->orWhere('wp_terms.term_id', 16323)
                        ->orWhere('wp_terms.term_id', 16320)
                        ->orWhere('wp_terms.term_id', 16321)
                        ->orWhere('wp_terms.term_id', 16322)
                        ->orWhere('wp_terms.term_id', 16327)
                        ->orWhere('wp_terms.term_id', 16324)
                        ->orWhere('wp_terms.term_id', 16325)
                        ->orWhere('wp_terms.term_id', 16326)
                        ->orWhere('wp_terms.term_id', 16445)
                        ->orWhere('wp_terms.term_id', 16446)
                        ->orWhere('wp_terms.term_id', 16447)
                        ->orWhere('wp_terms.term_id', 16331)
                        ->orWhere('wp_terms.term_id', 16328)
                        ->orWhere('wp_terms.term_id', 16329)
                        ->orWhere('wp_terms.term_id', 16330);
                    })
                ->get();


            foreach ($tartypes as $tartype) {
                echo "incident type :" .$tartype->name. "</br>";
                echo "ID :" .$tartype->post_id. "</br>";
            }
            // if ($icats->isNotEmpty()){
            //     echo "ada data";
            // }else{
            //     echo "tidak ada data";
            // }

    }
}
